### PR TITLE
#14 Estimate project size

### PR DESCRIPTION
**Pull request by super132**
For task #14, provide estimate based on the components and my knowledge.

### CODE REVIEW

**Comment by super132** [comment]
@dmarkov , would you please review this PR? Thanks.

**Comment by dmarkov** [comment]
@super132 Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@caarlos0 could you please review this pull request

**Comment by dmarkov** [comment]
> @dmarkov , would you please review this PR? Thanks.

@super132 thanks, I'll take a look

**Comment by caarlos0** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@caarlos0 Many thanks! **16 mins** were added to your account in Transaction ID `AP-6N216340L50958241` (task took 44 hours and 27 mins)

extra minutes for review comments (c=1)

added +16 to your rating, now it is equal to [+2074](http://www.netbout.com/b/35095?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
