### PR TITLE
#8 Explained the plugin purpose in more detail

### PR DESCRIPTION
**Pull request by Suseika**
For task #8, added more specific explanation of what this plugin is supposed to do.

### CODE REVIEW

**Comment by Suseika** [comment]
@dmarkov Would you pease review this PR? Thanks.

**Comment by dmarkov** [comment]
@suseika I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@longtimeago please review this PR

**Comment by Suseika** [comment]
@longtimeago Review this PR please, it's been quite some time.

**Comment by longtimeago** [comment]
@Suseika Sorry for the delay, I missed the notification. Thank you!

**Comment by longtimeago** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
