### PR TITLE
Issue 10

### PR DESCRIPTION
**Pull request by dpisarenko**
Issue: https://github.com/jcabi/jcabi-latex-maven-plugin/issues/10

### CODE REVIEW

**Comment by dmarkov** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@carlosmiranda this pull request is for you, please review

**Comment by carlosmiranda** [comment]
@rultor Let's merge now please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@carlosmiranda I added **16 mins** to your account, many thanks for working with the project!. added +16 to your rating, now it is equal to [+1320](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
