### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@yegor256 review this pull request please, it is rather short for a full review

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 I just added **17 mins** to your account, many thanks for your contribution (000-72b31ed9).. 68 hours and 52 mins spent here

review comments (c=2) added as a bonus

+17 to your rating, your total score is [+4368](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
